### ISSUE TITLE
bug in filename

### ISSUE THREAD

**Issue by JHelmetDago** [firegento/firegento-customer#1]
\app\code\community\FireGento\Customer\sql\firegento_customer_setup\install-0.1.0.php should be mysql4-install-0.1.0.php.

otherwise the installation file is not achieved and the attributes are not installed.

so happen in a fresh magento 1.6.1 installation. 

however thanks for your work

**Comment by therouv** [comment]
Can't reproduce this issue - Works perfectly fine on a fresh 1.6.1.0 installation.

Magento changed the logic for the setup script filenames since giving the possibility to use other databases like Oracle. So "install-0.1.0.php" is the correct way and "mysql4-install-0.1.0.php" would be the old way.
